# Generated by Django 5.0.5 on 2024-05-08 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(blank=True, max_length=500, null=True)),
                ('weight_in_kg', models.IntegerField()),
                ('length_in_cm', models.IntegerField()),
                ('height_in_cm', models.IntegerField()),
                ('width_in_cm', models.IntegerField()),
                ('name_of_shipper', models.CharField(max_length=500)),
                ('Recievers_name', models.CharField(max_length=500)),
                ('product', models.CharField(max_length=500)),
                ('Origin', models.CharField(max_length=500)),
                ('Destination', models.CharField(max_length=500)),
                ('Departure_time', models.TimeField(blank=True, null=True)),
                ('departure_date', models.DateField(blank=True, null=True)),
                ('pickup_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=500, null=True)),
                ('longitude', models.CharField(blank=True, max_length=500, null=True)),
                ('lattitude', models.CharField(blank=True, max_length=500, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
