# Generated by Django 5.0.5 on 2024-05-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allen_exprees_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='shipment_status',
            field=models.CharField(blank=True, choices=[('Dispatched', 'Dispatched'), ('Failed Attempt', 'Failed Attempt'), ('Delayed', 'Delayed')], max_length=500, null=True),
        ),
    ]
